In [1]:
import pandas as pd
import numpy as np
from sklearn.datasets import make_regression

In [43]:
X,y = make_regression(n_samples = 1000,n_features = 4,noise = 25)

In [44]:
from sklearn.linear_model import LinearRegression

In [45]:
lr = LinearRegression()

Scikit-Learn class Multiple LinearRegression

In [50]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size = 0.2)

In [51]:
lr.fit(X_train,y_train)

LinearRegression()

In [62]:
lr.coef_

array([37.485471  ,  6.12047637, 39.10571707, 15.71954895])

In [63]:
lr.intercept_

0.6971541714767686

In [52]:
y_pred = lr.predict(X_test)

In [53]:
from sklearn.metrics import r2_score
r2_score(y_test,y_pred)

0.8094753493414777

Mathematical Formulation of Multiple LinearRegression

In [115]:
class Mylr:
    def __init__(self):
        self.coef_ = None
        self.intercept_ = None

    def fit(self,X_train,y_train):
        X_train = np.insert(X_train,0,1,axis = 1)
        result = np.linalg.inv(np.dot(X_train.T,X_train)).dot(X_train.T).dot(y_train)
        self.intercept_ = result[0]
        self.coef_ = result[1:]

    def predict(self,X_test): 
        a = np.dot(X_test,self.coef_.reshape(-1,1))+self.intercept_
        return a



In [116]:
Lr = Mylr()

In [117]:
Lr.fit(X_train,y_train)

In [118]:
Lr.coef_

array([37.485471  ,  6.12047637, 39.10571707, 15.71954895])

In [119]:
Lr.intercept_

0.6971541714767696

In [125]:
y_pred = Lr.predict(X_test)

In [123]:
lr.predict(X_test)

array([  45.03010109,  -42.40683589,   81.65849535,   90.64247483,
        -35.00101858,  -72.61749929,  -55.88506709,   -1.89144472,
        -93.48670347, -107.25985363,  -44.04216285,   72.30925135,
          2.83101008,  -65.82245412,   30.43438603,    4.7766089 ,
        107.37810633,   29.95309336,    8.48587037,  -36.89908862,
        -37.34416199,    4.85298464,   26.68529948,    4.61461408,
        -72.53952506,   -1.39766021,  -55.04580199,    3.87021518,
        124.31789828,   46.45838288,   64.75909169,  -71.0046737 ,
          6.63709717,  -99.90441433,  -33.75766296,   55.68125747,
          3.41323586, -100.58952547,  -73.03752013,   10.63018155,
        -27.69566894,   76.42720999,    5.39701452,   62.03558576,
        -76.08861708,  -48.13399012,   -1.72398534,   13.66895042,
        -45.52672405,   86.92497325, -108.24830157,  -99.88401793,
         -8.62416223,  -56.46000108,  -55.6514719 ,   10.69314538,
         19.75347354,  -79.50692216,   10.10268676,  -62.99895